# Generated by Django 4.2.16 on 2025-12-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateexercise',
            name='target_reps',
            field=models.PositiveIntegerField(default=0, help_text='Target reps as number (for reference)'),
        ),
    ]
