# Generated by Django 4.2.16 on 2025-12-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_remove_exercise_video_url'),
        ('workouts', '0002_templateexercise_target_reps'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('weight_kg', models.FloatField(default=0)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('rpe', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutexercise')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.RemoveField(
            model_name='templateexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workouttemplate',
            name='is_ai_generated',
        ),
        migrations.AlterField(
            model_name='templateexercise',
            name='target_reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SessionLog',
        ),
    ]
