# Generated by Django 4.2.16 on 2025-12-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutexercise_workoutset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttemplate',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
