# Generated by Django 4.2.16 on 2025-12-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='badge_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
