# Generated by Django 4.2.16 on 2025-12-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitware', '0004_merge_20251219_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='fitware.goal'),
        ),
        migrations.AddField(
            model_name='challengejoined',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
