# Generated by Django 5.2.9 on 2025-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='start_value',
            field=models.FloatField(default=0),
        ),
    ]
