# Generated by Django 4.2.16 on 2025-12-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitware', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='goal',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs'), ('fav', 'Body Fat %'), ('km', 'Kilometers'), ('m', 'Meters'), ('miles', 'Miles'), ('laps', 'Laps'), ('min', 'Minutes'), ('hr', 'Hours'), ('workouts', 'Workouts'), ('sets', 'Sets'), ('reps', 'Reps'), ('cal', 'Calories')], default='workouts', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
