# Generated by Django 4.2.16 on 2025-12-18 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitware', '0002_challenge_badge_name_challenge_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='target_value',
            field=models.FloatField(default=0, help_text='Target amount, e.g. 20 for 20km or 10 for 10 workouts'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='unit',
            field=models.CharField(choices=[('km', 'Kilometer'), ('workouts', 'Workouts'), ('minutes', 'Minutes'), ('reps', 'Repetitions'), ('kg', 'Kilogram')], default='workouts', help_text='Unit of the challenge target', max_length=20),
        ),
        migrations.AddField(
            model_name='challengejoined',
            name='progress_value',
            field=models.FloatField(default=0, help_text="User's current progress in challenge units"),
        ),
        migrations.AddField(
            model_name='challengejoined',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='challengejoined',
            unique_together={('user', 'challenge')},
        ),
    ]
