# Generated by Django 4.2.16 on 2025-12-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitware', '0002_remove_goal_due_date_alter_goal_unit_activitylog'),
        ('fitware', '0003_challenge_target_value_challenge_unit_and_more'),
    ]

    operations = [
    ]
