# Generated by Django 4.2.16 on 2025-12-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitware', '0004_merge_20251219_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
