# Generated by Django 4.2.16 on 2025-12-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitware', '0005_challenge_goal_challengejoined_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='unit',
            field=models.CharField(choices=[('km', 'Kilometer'), ('m', 'Meters'), ('miles', 'Miles'), ('workouts', 'Workouts'), ('minutes', 'Minutes'), ('min', 'Minutes (short)'), ('hr', 'Hours'), ('sets', 'Sets'), ('reps', 'Repetitions'), ('kg', 'Kilogram'), ('lbs', 'Pounds'), ('laps', 'Laps'), ('cal', 'Calories'), ('fav', 'Body Fat %')], default='workouts', help_text='Unit of the challenge target', max_length=20),
        ),
    ]
