# Generated by Django 5.2.9 on 2025-12-22 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitware', '0008_alter_activitylog_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activitylog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='activitylog',
            unique_together={('user', 'date', 'action_type')},
        ),
    ]
