# Generated by Django 5.2.9 on 2025-12-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility')], max_length=50)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('metric_type', models.CharField(choices=[('weight', 'Weight (kg/lbs)'), ('distance', 'Distance (km/mi)'), ('time', 'Time (duration)'), ('reps', 'Reps Only')], default='weight', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='exercises_e_name_9bce89_idx')],
                'unique_together': {('name', 'created_by')},
            },
        ),
    ]
